from src.generators.generator_ollama import OllamaGenerator
from src.generators.generator import Generator
from src.generators.stable_diffusion_generator import StableDiffusionImageGenerator
from src.generators.falai_image_generator import FalAiImageGenerator
from src.generators.proxy_sd_generator import ProxySDImageGenerator
